### ISSUE TITLE
Add teardown_interval to close connections after certain amount of time has passes

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-input-redis#33]
The Shippers establish a TCP connection to Redis and never drop it, if you have a load balancer, the balance of load depends on the initial triaging by the load balancer. (in other words, once a running Shipper connects to a Redis it will stay connected to that Redis). At times the overwhelming majority are connected to a Redis instance.

Adding a teardown internal and closing the connection after several minutes will allow to release old connections and refresh the connection which is very useful for load balancing instances.

**Comment by jordansissel** [comment]
> Adding a teardown internal and closing the connection after several minutes

(What follows is mostly a brain dump, so we can discuss whatever we need further since I haven't realy fully formed some of the ideas here)

Not sure I understand this request. If we close and reconnect periodically, we'll be stalling the output for at least one network roundtrip (3 roundtrips SSL is ever used) without a strong reason to do so by default.

In my opinion, it is somewhat of a mistake to try and use a load balancer in a scenario in which it is incapable of actually sharing load - in the described scenario, the load balancer is more like a connection balancer and is agnostic to the actual resource consumption (load) on those connections. In this respect, the idea to reconnect periodically is kind of a band-aid hack upon an already poorly-working piece of infrastructure (a load balancer in this scenario).

That said, I won't reject this proposal yet because I do think that even while not the right tool for this job, many folks will probably stick load balancers in between Logstash and Redis. How many, I don't know. ;)

So let me try approaching this from a different angle - What is the negative impact of an imbalance in redis connectivity? For example, if you have 2 redis servers behind a load balanacer, and 90% of connections are on Redis 1 and 10% are on Redis 2 - what is the negative impact?

**Comment by jordansissel** [comment]
Also possibly notable, I believe load balancers can be configured to balance based on connection counts. For example, haproxy's `balance leastconn` will choose the backend (redis, in this scenario) with the fewest connections.

Can you tell me more about the specific load balancer being used in this scenario?

**Comment by untergeek** [comment]
Least connections is the best possible load-balancer approach, IMO, notably because of the observed phenomenon.  Redis wants a persistent connection, so you should change your load balancer to work with that.  If you need clustering, well, we should update the plugin to work with the new Redis Sentinel stuff.

**Comment by rferrante1966** [comment]
@jordansissel :  our loadbalancers are  F5 LTM BIG-IP and they do support a least connections option. 

Our architecture (whether ideal or not) includes load balancing a fleet of independent redis servers where each of those redis servers are on a host with a logstash indexer and an elasticsearch client node.  It was designed to scale up by adding additional hosts (with redis/logstash/elastic-client) as needed. 

Tearing down the shipper connection to Redis periodically (we do it every five minutes) gives the load balancer an opportunity to balance the load (using whatever LB method is selected).  Least-connections could be best if all the redis/logstash/elastic-client nodes were very similar in capacity, but where capacities differ a weighted method may be better.

**Comment by gmoskovicz** [comment]
@jordansissel @untergeek Any news about this?

**Comment by jordansissel** [comment]
@rferrante1966 My preference would be to have Logstash do the balancing itself, if we need something like this, since we could balance more closely to the work cost (events) rather than something unrelated to work (connection count).

Some question:
* Can your load balancers be configured to terminate connections older than 5 minutes?
* What is the negative impact of Logstash behaving the way it does today - can you describe your experience and observations?
* If you disagree that the logstash redis output should not balance on its own, can you help me understand why?

**Comment by rferrante1966** [comment]
@jordansissel: 
*  I'll check on the whether the loadbalancer can tear down connections after a time period, but I'm not sure that would be a good idea even if possible.   
*  Having Logstash maintain a perpetual connection doesn't give the load balancer an opportunity to redistribute the load (according to whatever algorithm we configure it to use).  Presently once connected to a Redis [and upstream to] its associated Indexer(s) the connections are fixed.  We have seen this lead to uneven distribution of load and when we looked into it we realized that nailing up a static connection just does not effectively leverage the load balancers.   
* We have a large (potentially growing to very large) number of Logstash shippers.  If they each attempted to load balance across our fleet of indexers effectively it could work.  However, load balancing is a enterprise service that we are leveraging presently and it seems to make some sense to simplify the work of the shippers and have a dedicated load balancer focused on balancing the load, which is something they can do only if the connections are torn down periodically or after each batch.

**Comment by jordansissel** [comment]
@rferrante1966 What is the negative impact of Logstash behaving the way it does today - can you describe your experiences and observations?

**Comment by rferrante1966** [comment]
Without the teardown_interval (we hack it into the code today) we were seeing that each Shipper tcp connection was somewhat permanently nailed up to one Redis.  The downside was that load balancing could only be done at the time that semi-permanent connections were established.  We were seeing cases where there was uneven distribution of the use of our independent load-balanced Redis queues. (e.g. all our high throughput shippers were on one Redis).  

With the connections torn-down every five minutes by the shippers we are seeing much more balanced distribution of load.

**Comment by jordansissel** [comment]
> there was uneven distribution

what is the negative impact of this uneven distribution?

**Comment by rferrante1966** [comment]
The negative impact was more inconsistent customer experience in terms of the latency between the logging and availability for Kibana search.  One customer might have just a few seconds from logging a message to searching and finding it Kibana, while another customer might have a few minutes.  

We plan to scale up later this year by adding hosts to our load_balanced pool of queue/indexer/client_node hosts.   Having the teardown_interval feature will optimize the use of this pool.

**Comment by jordansissel** [comment]
Instead of using redis, can you use the lumberjack protocol instead? Lumberjack clients will detect slow-downs and stalls and will try a new connection to compensate. This is possible because the lumberjack protocol has read acknowledgements (redis lists do not) so it can compute the latency of a given payload to be processed. This would give you a load-based teardown-and-retry with the additional benefit of not having to deploy a redis node to all your logstash servers.

Alternately, if you are really deploying a 1 redis node per logstash indexer, then I would suggest that this is the cause of your scaling problems. The way Logstash uses redis was built with the idea that Redis is used as a message broker (with multiple consumers and multiple publishers); in your scenario, there's only ever 1 consumer (for each redis node). Moving away from a single-consumer model will help your situation because you can have each Logstash indexer read from all redis nodes and you will have pretty good load distribution given that each Logstash node will be operating "as fast as it can" on the data available, rather than only on data available from a single redis node (per Logstash node). In doing this, you could remove the need for your F5, dramatically reduce the number of Redis nodes, and improve throughput of your Logstash indexers by allowing them the opportunity to process _any_ event, not just events directed at a localhost redis node.

**Comment by rferrante1966** [comment]
Lumberjack protocol sounds like a good approach.  Lumberjack is used in the FileBeat, right? It's not an option with Logstash proper, right?  We would like to migrate to FileBeat but are waiting on filtering and multiline features to appear in the product.  

It sounds like you are not a fan of our architecture with F5 load-balancer in front of a set of redis-logstash-client_node boxes (one indexer per redis).  That was architected (with support from Elastic.co) prior to my joining the team.  At some point this year we will need to revisit the architecture. Until then we were hoping to make an incremental improvement with the teardown_interval feature.

Rick

**Comment by jordansissel** [comment]
@rferrante1966 lumberjack input/output are plugins for Logstash. The protocol is used by beats input and lumberjack inputs. You can send from logstash-to-logstash using the lumberjack output and sending to a remote lumberjack input. This would remove redis as a component in your architecture.

As for making an incremental improvement, I agree that would probably be the smoothest option for you. Given that it sounds like you already have this teardown_interval feature in your plugin, and given that I'm still not convinced it's the right solution to include in the released plugin, can you continue maintaining your fork of this plugin - and if not, why not?

**Comment by jordansissel** [comment]
(My last comment was probably lacking in detail, so let me know if you need any other info - happy to talk through this further)

**Comment by suyograo** [comment]
Not fixing this for aforementioned reasons.
